### PR TITLE
Enhanced fonts on list and Added Start + End date separately

### PR DESCRIPTION
**Pull request by RSickenberg**
Hey, I found some glitches for the service name font at init, so I tweaked this.

And Added start date + end date at the bottom of the eventMessage since the place is not an issue and the information may be relevant :)

Regards

### CODE REVIEW

**Comment by insidegui** [comment]
Thank you @RSickenberg!

I do like that you fixed that annoying title bug.

I don't like the way the app looks with both start and end dates below the description, it looks way too busy. I don't really have any suggestion as to how we could make the layout look better with that extra info in there, so I'd appreciate if you could experiment with it a little bit :)

In the meantime, if you could open a separate PR just with the title fix, that would be great.

**Comment by RSickenberg** [comment]
Hello @insidegui !

Thanks for your feedback, I will investigate for a nicer layout and make an extra PR for the label fixes :)

Best regards,
Romain Sickenberg

**Comment by RSickenberg** [comment]
@insidegui 
Here you go, I added a popover for the Circle to show the start and end date. Let me know if it's okay for you.

I thought a (ℹ️) would be maybe appropriate but would take more space.

Regards

**Comment by insidegui** [comment]
Much better!

Just two more things before we can merge it:

- Remove the `PST` suffix from dates, since they are converted to the local timezone when formatting
- Adjust the layout of the popover, I tweaked the popover contents by using the implementation below and it looks much better

```swift
VStack(alignment: .trailing, spacing: 6) {
    Text(self.service.eventStartDate)
    Text(self.service.eventEndDate)
}
.foregroundColor(Color(.secondaryLabelColor))
.font(.system(size: 11))
.padding()
```

Screen Shot 2020-03-01 at 11 37 19

**Comment by RSickenberg** [comment]
Here you go!

Many thanks for the review and the feedback! Was an honor and a privilege.

Regards,
Romain Sickenberg

**Comment by insidegui** [comment]
Awesome! Thank you for contributing.

Let's ship it 🚀

**Pull request merged**
